---
- name: Create a systemd service file
  ansible.builtin.template:
    src: k3s.service.j2
    dest: "/etc/systemd/system/{{ k3s_service_name }}.service"
    owner: root
    group: root
    mode: 0640
  register: k3s_systemd_service_file_result
- name: "Reload systemd"
  ansible.builtin.systemd_service:
    name: "{{ k3s_service_name }}.service"
    daemon_reload: true
  when: "k3s_systemd_service_file_result is changed"
- name: "Enable the {{ k3s_service_name}} service"
  ansible.builtin.systemd_service:
    name: "{{ k3s_service_name }}.service"
    enabled: true
- name: "Restart the {{ k3s_service_name }} service"
  ansible.builtin.service:
    name: "{{ k3s_service_name }}"
    state: restarted
  when: "k3s_download_result is changed or k3s_systemd_service_file_result is changed"
- name: "Start the {{ k3s_service_name }} service"
  ansible.builtin.service:
    name: "{{ k3s_service_name }}"
    state: started
  when: "not (k3s_download_result is changed) and not (k3s_systemd_service_file_result is changed)"
